// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMwjQ3W1DkF90NoEgw3wHlntFTDFSjOpA',
    appId: '1:1065381426000:web:3d8dc0e7d9e6a0a282b255',
    messagingSenderId: '1065381426000',
    projectId: 'tardefinal-69fa5',
    authDomain: 'tardefinal-69fa5.firebaseapp.com',
    storageBucket: 'tardefinal-69fa5.appspot.com',
    measurementId: 'G-6BMCMKBLVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmMZjOd0DLHIupDplpY8TCE346h-0H6Gk',
    appId: '1:1065381426000:android:8244436676b0bbc382b255',
    messagingSenderId: '1065381426000',
    projectId: 'tardefinal-69fa5',
    storageBucket: 'tardefinal-69fa5.appspot.com',
  );
}
